<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<SelfContained>True</SelfContained>
		<IncludeNativeLibrariesForSelfExtract>True</IncludeNativeLibrariesForSelfExtract>
		<CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/BolotnikovPS/TBotPlatform</RepositoryUrl>
		<Description>C# библиотека для облегчения создания бота Telegram</Description>
		<Version>2.1.2-beta7</Version>
		<IncludeSymbols>True</IncludeSymbols>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="TBotPlatform.Tests" />
	</ItemGroup>
	
	<ItemGroup>
		<Compile Update="**\StateContext.*.cs">
			<DependentUpon>StateContext.cs</DependentUpon>
		</Compile>
		<Compile Update="**\StateFactory.*.cs">
			<DependentUpon>StateFactory.cs</DependentUpon>
		</Compile>
		<Compile Update="**\BotBuilder.*.cs">
			<DependentUpon>BotBuilder.cs</DependentUpon>
		</Compile>
		<Compile Update="**\DependencyInjection.*.cs">
			<DependentUpon>DependencyInjection.cs</DependentUpon>
		</Compile>
		<Compile Update="Extensions.*.cs">
			<DependentUpon>Extensions.cs</DependentUpon>
		</Compile>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\LICENSE.md" Pack="true" PackagePath="" />
		<None Include="..\README.md" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.Redis" PrivateAssets="compile" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" PrivateAssets="compile" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="RateLimiter" />
		<PackageReference Include="Telegram.Bot" />
		<PackageReference Include="ZiggyCreatures.FusionCache" />
		<PackageReference Include="ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson" PrivateAssets="compile" />
	</ItemGroup>
	
</Project>
